training: !!bool "true"
testing: !!bool "true"
device: "cuda"
unprocessed_data: '/home/momozyc/Music/audioData/TIMIT(wav)/*/*/*/*.WAV'
---
data:
    train_path: './train_tisv'
    train_path_unprocessed: '/home/momozyc/Music/audioData/TIMIT(wav)/TRAIN/*/*/*.WAV'
    test_path: './test_tisv'
    zhouxingchi_path: './zhouxingchi_tisv'
    test_path_unprocessed: '/home/momozyc/Music/audioData/TIMIT(wav)/TEST/*/*/*.WAV'
    data_preprocessed: !!bool "true" 
    sr: 16000
    nfft: 512 #For mel spectrogram preprocess
    window: 0.025 #(s)
    hop: 0.01 #(s)
    nmels: 40 #Number of mel energies
    tisv_frame: 180 #Max number of time steps in input after preprocess
---   
model:
    hidden: 768 #Number of LSTM hidden layer units
    num_layer: 4 #Number of LSTM layers
    proj: 256 #Embedding size
    lastlinear: 256 #
    model_path: './speech_id_checkpoint/ckpt_epoch_960_batch_id_246.pth' #Model path for testing, inference, or resuming training
    pretrain_model: 'ckpt_epoch_960_batch_id_6.pth'
---
train:
    N : 6 #Number of speakers in batch
    M : 7 #Number of utterances per speaker
    num_workers: 3 #number of workers for dataloader
    lr: 0.1 
    epochs: 180000 #Max training speaker epoch 
    log_interval: 30 #Epochs before printing progress
    log_file: './speech_id_checkpoint/Stats'
    checkpoint_interval: 120 #Save model after x speaker epochs
    checkpoint_dir: './speech_id_checkpoint'
    restore: !!bool "true" #Resume training from previous model path
---
test:
    N : 4 #Number of speakers in batch
    M : 10 #Number of utterances per speaker
    num_workers: 8 #number of workers for data laoder
    epochs: 10 #testing speaker epochs
